stages:
  - build
  - security
  - test
  - review
  - deploy

bundle_secutiy_audit:
  extends: .ruby_base
  allow_failure: false
  stage: security
  script:
    - gem install bundler-audit
    - bundle audit check --update
   only:
    - merge_requests
    - pushes
    
rubocop:
  extends: .ruby_base
  stage: review
  allow_failure: false
  artifacts:
    name: rubocop_report
    when: always
    paths:
      - rubocop/
    expire_in: 1 week
  script:
    - gem install rubocop
    - gem install rubocop-rails
    - gem install rubocop-md
    - gem install rubocop-performance
    - gem install rubocop-rspec
    - rubocop --format html -o rubocop/index.html
  only: 
    - merge_requests
    
rubycritic:
  extends: .ruby_base
  stage: review
  allow_failure: false
  artifacts:
    name: rubycritic_report
    when: always
    paths:
      - tmp/rubycritic/
    expire_in: 1 week
  script:
    - gem install rubycritic
    - rubycritic
  only: 
    - merge_requests

brakeman:
  extends: .ruby_base
  stage: review
  allow_failure: false
  artifacts:
    name: brakeman_report
    when: always
    paths:
      - brakeman/
    expire_in: 1 week
  script:
    - gem install brakeman
    - brakeman --format html -o brakeman/index.html
  only: 
    - merge_requests

license_finder:
  extends: .ruby_base
  stage: security
  allow_failure: false
  script:
    - source ~/.profile
    - gem install bundler
    - gem install license_finder
    - bundle install --path vendor/bundle
    - license_finder
  only: 
    - merge_requests

rails_best_pratices:
  extends: .ruby_base
  stage: review
  allow_failure: true
  artifacts:
    name: rails_best_practices_report
    when: always
    paths:
      - rails_best_practices/
    expire_in: 1 week
  script:
    - gem install rails_best_practices
    - mkdir rails_best_practices
    - rails_best_practices -f html . --output-file rails_best_practices/index.html
  only: 
    - merge_requests
